image: ubuntu:16.04

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -y -qq curl
  - curl -sL https://deb.nodesource.com/setup_12.x | | sudo -E bash -
  - apt-get install -y -qq nodejs
  - node -v
  - npm -v
  - npm install

test:
  script:
    - npm test
