image: node:12

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install
  - mkdir -p ~/.ssh
  - echo -e "$SECRET_KEY" > ~/.ssh/id_rsa
  - chmod 600  ~/.ssh/id_rsa
  - echo -e "host gite.lirmm.fr\n HostName gite.lirmm.fr\n IdentityFile ~/.ssh/id_rsa\n User git" > ~/.ssh/config

Test:
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn test
