image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -y -qq curl
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt-get install -y -qq nodejs
  - node -v
  - npm -v
  - mkdir -p ~/.ssh
  - echo -e "$SECRET_KEY" > ~/.ssh/id_rsa
  - chmod 600  ~/.ssh/id_rsa
  - echo -e "host gite.lirmm.fr\n HostName gite.lirmm.fr\n IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test
